quirk_names = [
    'Babys First Quirk: Energy Power',
    'Babys First Quirk: Energy Cap',
    'Babys First Quirk: Energy Bars',
    'Babys First Quirk: Magic Power',
    'Babys First Quirk: Magic Cap',
    'Babys First Quirk: Magic Bars',
    'Babys First Quirk: Adventure',
    'Stat Boost For Rich Quirks I',
    'Adventure Boost For Rich Quirks I',
    'GOOOOOLLLLLLLLLLLD!',
    'The Beasts Special Beard Tonic',
    'Beasted Boosts I',
    'The Beasts Seed ;)',
    'The Beasts Fertilizer',
    'The Beast NGU Perk',
    'Energy Wandoos BEAST-a',
    'Magic Wandoos BEAST-a',
    'Super Advanced Beast Training!',
    'Accessory Slot!',
    'MacGuffin Slot!',
    'Adv. Training Level Bank I',
    'Adv. Training Level Bank II',
    'Adv. Training Level Bank III',
    'Adv. Training Level Bank IV',
    'Adv. Training Level Bank V',
    'Time Machine Level Bank I',
    'Time Machine Level Bank II',
    'Time Machine Level Bank III',
    'Time Machine Level Bank IV',
    'Time Machine Level Bank V',
    'Beard Temp Level Bank I',
    'Beard Temp Level Bank II',
    'Beard Temp Level Bank III',
    'Beard Temp Level Bank IV',
    'Beard Temp Level Bank V',
    'Generic Energy Power Quirk I',
    'Generic Energy Cap Quirk I',
    'Generic Energy Bars Quirk I',
    'Generic Magic Power Quirk I',
    'Generic Magic Cap Quirk I',
    'Generic Magic Bars Quirk I',
    'Generic Energy Power Quirk II',
    'Generic Energy Cap Quirk II',
    'Generic Energy Bars Quirk II',
    'Generic Magic Power Quirk II',
    'Generic Magic Cap Quirk II',
    'Generic Magic Bars Quirk II',
    'Generic Resource 3 Power Quirk I',
    'Generic Resource 3 Cap Quirk I',
    'Generic Resource 3 Bars Quirk I',
    'Another MacGuffin Slot!',
    'Stat Boost For Rich Quirks II',
    'Adventure Boost For Rich Quirks II',
    'Beasted Boosts II',
    'Lower Minmum Wish Speed?',
    'An Inventory Automerge Slot',
    'A Wish Slot',
    'Atk/Def Hack Milestone Reducer I',
    'PP Hack Milestone Reducer I',
    'EXP Hack Milestone Reducer I',
    'Wish Hack Milestone Reducer I'
]

itopod_perk_name = ['The Newbie Energy Perk', 'The Newbie Magic Perk', 'The Newbie Adventure Perk', 'The Newbie Drop Chance Perk', 'The Newbie Stat Perk', 'Stat Boost For Rich Perks I', 'Generic Energy Power Perk I', 'Generic Energy Bar Perk I', 'Generic Energy Cap Perk I', 'Generic Magic Power Perk I', 'Generic Magic Bar Perk I', 'Generic Magic Cap Perk I', 'Boosted Boosts I', 'Faster NGU Energy', 'Faster NGU Magic', 'Double Basic Training', 'Quicker Fruit of Power ОІ Bonus Activation', 'Quicker Fruit of Numbers Bonus Activation', 'Instant Advanced Training Levels', '"Fruit of Knowledge sucks 1/5"', '"Fruit of Knowledge STILL sucks 1/5"', "Five O'Clock Shadow", 'Wandoos Lover', 'Golden Showers', 'I want your seeds ;)', "The Loot Goblin's Blessing", 'Improved Cube Boosting!', "Daycare Kitty's Blessing I", "Daycare Kitty's Blessing II", "You'll Really Want This", 'What a Crappy Perk', 'More Inventory Space I', 'More Inventory Space II', 'Boosted Boosts II', 'Bonus Titan EXP!', 'Bonus Boss EXP!', 'Adv. Training Level Bank I', 'Adv. Training Level Bank II', 'Adv. Training Level Bank III', 'Adv. Training Level Bank IV', 'Adv. Training Level Bank V', 'Time Machine Level Bank I', 'Time Machine Level Bank II', 'Time Machine Level Bank III', 'Time Machine Level Bank IV', 'Time Machine Level Bank V', 'Beard Temp Level Bank I', 'Beard Temp Level Bank II', 'Beard Temp Level Bank III', 'Beard Temp Level Bank IV', 'Beard Temp Level Bank V', "The First Harvest's The Best", 'A Digger Slot!', 'Ooh, Another Digger Slot!', 'Stat Boost For Rich Perks II', 'Adventure Boost For Rich Perks I', 'MacGuffin Daycare!', 'Generic Energy Power Perk II', 'Generic Energy Bar Perk II', 'Generic Energy Cap Perk II', 'Generic Magic Power Perk II', 'Generic Magic Bar Perk II', 'Generic Magic Cap Perk II', 'Faster NGU Energy II', 'Faster NGU Magic II', 'Improved MacGuffin Drops I', 'A MacGuffin Slot!', 'Another MacGuffin Slot!', 'MacGuffin ITOPOD Drops!', 'Improved MacGuffin ITOPOD Drops I', 'Improved MacGuffin ITOPOD Drops II', 'Improved MacGuffin ITOPOD Drops III', 'Blood MacGuffin О± Spell!', 'Blood MacGuffin ОІ Spell!', 'Generic Energy Power Perk III', 'Generic Energy Bar Perk III', 'Generic Energy Cap Perk III', 'Generic Magic Power Perk III', 'Generic Magic Bar Perk III', 'Generic Magic Cap Perk III', 'Faster NGU Energy III', 'Faster NGU Magic III', 'Stat Boost For Rich Perks III', 'Adventure Boost For Rich Perks II', 'Iron Pill Also Sucks 1/5', 'Iron Pill Still Sucks 1/5', 'Daycare Slot! c:', 'Not So Minor Anymore', 'Another MacGuffin Slot!', 'Better QP Rewards!', 'Improved Quest Looting', 'Advanced Gooder Idle Questing', 'Even More Advanced Gooder Idle Questing', 'Spawn Faster Damnit', 'The Fibonacci Perk', 'Generic Resource 3 Power Perk I', 'Generic Resource 3 Bar Perk I', 'Generic Resource 3 Cap Perk I', 'Generic Resource 3 Power Perk II', 'Generic Resource 3 Bar Perk II', 'Generic Resource 3 Cap Perk II', 'Generic Resource 3 Power Perk III', 'Generic Resource 3 Bar Perk III', 'Generic Resource 3 Cap Perk III', 'Truly Idle Questing', 'Gooder Idle Questing!', 'Another Gooder Idle Questing!', 'Boosted Boosts III', 'Faster wishes I', 'Minimum Wish Time Reduction I', 'Minimum Wish Time Reduction II', 'An Inventory Merge Slot', 'Another Inventory Merge Slot', 'Adventure Hack Milestone Reducer I', 'Blood Hack Milestone Reducer I', 'Daycare Hack Milestone Reducer I', 'Generic Energy Power Perk IV', 'Generic Energy Bar Perk IV', 'Generic Energy Cap Perk IV', 'Generic Magic Power Perk IV', 'Generic Magic Bar Perk IV', 'Generic Magic Cap Perk IV', 'Generic Resource 3 Power Perk IV', 'Generic Resource 3 Bar Perk IV', 'Generic Resource 3 Cap Perk IV']
